### PR TITLE
Add release date prior to merge to master

### PR DESCRIPTION
**Pull request by MrCreosote**
Changes have been running in CI since the 5th

- [n/a] I updated the README.md docs to reflect this change.

For changes to the codebase:

- [n/a] I have written tests to cover this change.
- [x] This is not a breaking API change OR
- [ ] This is a breaking API change and I have incremented the API version and added a summary to CHANGELOG.md.

### CODE REVIEW

**Review by ialarmedalien — APPROVED** [review]

**Review by n1mus — COMMENTED** [review]
Why is this its own separate PR? And it's not even in the dev->main PR?

**Comment by MrCreosote** [comment]
> Why is this its own separate PR?

Which PR were you thinking it should be included in? Neither of the other two I did yesterday seemed appropriate to me

> And it's not even in the dev->main PR?

It is though?
https://github.com/kbase/relation_engine/pull/167/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR8

**Comment by ghost** [comment]
Sorry, ignore what I said. I almost immediately added an "Edit:" to my previous comment, saying that I realized you did this because develop is a protected branch. So you have to PR any random stuff in.

**Comment by MrCreosote** [comment]
I never push directly to develop or master for any kbase repos

**Pull request merged**
