### PR TITLE
Show update source

### PR DESCRIPTION
**Pull request by jayrbolton**
Show the file path or URL of where we pulled the specs from when we run an update. This will be very useful for me, as often this can be a mystery and I have to debug the config.

We could write a test to show this works for a URL source, but I think not very necessary

For changes to the codebase:

- [x] I have written tests to cover this change.
- [x] This is not a breaking API change OR
- [ ] This is a breaking API change and I have incremented the API version and added a summary to CHANGELOG.md.

### CODE REVIEW

**Comment by ialarmedalien** [comment]
Can you remove the first two commits, since they are part of the other PR? Looks good otherwise.

**Comment by jayrbolton** [comment]
This was branched from `simplify-workflow`. I'll unbranch it so it's more quickly mergeable

**Comment by jayrbolton** [comment]
Done

**Comment by jayrbolton** [comment]
Forgot the VERSION and CHANGELOG.md

**Pull request merged**
