### PR TITLE
Small alteration to results structure

### PR DESCRIPTION
**Pull request by ialarmedalien**
- [x] I updated the README.md docs to reflect this change.
- [x] This is not a breaking API change OR

### CODE REVIEW

**Comment by jayrbolton** [comment]
How/where is this "coerce" property used and what is its purpose? I'm having a hard time finding anything.

**Comment by jayrbolton** [comment]
Test failure might be intermittent?
Happy to merge this, but also would like to know more what's going on

**Comment by jayrbolton** [comment]
Something very funky is going on with gunicorn in the tests on github

**Comment by ialarmedalien** [comment]
I'm using the "coerce" property in another set of tests that are running off the same file.

The test failure issue seems to be due to a new release of `greenlet`, which has changed the size of the binary:

```
/usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144
```

I've pinned the greenlet version to the previous version in the dependencies as a temporary fix.

**Comment by jayrbolton** [comment]
Another test in a different repo? Because I don't see the "coerce" property being used anywhere here.

**Comment by ialarmedalien** [comment]
yes, in the kb_cytoscape app repo. Sorry, should have been clearer!

**Pull request merged**
