### PR TITLE
Update edge_type.yaml to align with exascale_data repo

### PR DESCRIPTION
**Pull request by izaakm**
- [ ] I updated the README.md docs to reflect this change.

For changes to the codebase:

- [ ] I have written tests to cover this change.
- [x] This is not a breaking API change OR
- [ ] This is a breaking API change and I have incremented the API version and added a summary to CHANGELOG.md.

Relation engine:

```
 $ RES_ROOT_DATA_PATH=../exascale_data/prerelease/ python -m importers.djornl.parser --dry-run
Parsing edge file /Users/m8z/src/exascale_data/prerelease/edge_data/AT-UU-KS-00-AA-01.tsv
Parsing edge file /Users/m8z/src/exascale_data/prerelease/edge_data/AT-UU-GA-01-AA-01.tsv
Parsing edge file /Users/m8z/src/exascale_data/prerelease/edge_data/AT-UU-PP-00-AA-01.tsv
Parsing edge file /Users/m8z/src/exascale_data/prerelease/edge_data/AT-UU-RE-00-AA-01.tsv
Parsing edge file /Users/m8z/src/exascale_data/prerelease/edge_data/AT-UU-RP-03-AA-01.tsv
Parsing edge file /Users/m8z/src/exascale_data/prerelease/edge_data/AT-UU-CD-00-AA-01.tsv
Parsing edge file /Users/m8z/src/exascale_data/prerelease/edge_data/AT-UU-RX-00-AA-01.tsv
Parsing node file /Users/m8z/src/exascale_data/prerelease/aranet2-aragwas-MERGED-AMW-v2_091319_nodeTable.csv
Parsing cluster file /Users/m8z/src/exascale_data/prerelease/cluster_data/out.aranetv2_subnet_AT-CX_top10percent_anno_AF_082919.abc.I2_named.tsv
Parsing cluster file /Users/m8z/src/exascale_data/prerelease/cluster_data/out.aranetv2_subnet_AT-CX_top10percent_anno_AF_082919.abc.I4_named.tsv
Parsing cluster file /Users/m8z/src/exascale_data/prerelease/cluster_data/out.aranetv2_subnet_AT-CX_top10percent_anno_AF_082919.abc.I6_named.tsv

 26745 Total nodes
711040 Total edges
 25108 Nodes in edge
---
Node Types
  5069 No type
 21669 gene
     7 pheno
---
Edge Types
 94952 AT-UU-KS-00-AA-01
 82900 AT-UU-GA-01-AA-01
317441 AT-UU-PP-00-AA-01
  1359 AT-UU-RE-00-AA-01
167851 AT-UU-RP-03-AA-01
 25000 AT-UU-CD-00-AA-01
 21537 AT-UU-RX-00-AA-01
---
Node data available
  5069 Key only
     0 Cluster
 21676 Full
---
     0 Errors
```

### CODE REVIEW

**Review by ialarmedalien — APPROVED** [review]
👍

**Comment by ialarmedalien** [comment]
@izaakm  if you can resolve the conflicts and push the updated branch, this can be merged.

**Comment by dakotablair** [comment]
These changes are included in PR #87 with all conflicts resolved.

**Comment by dakotablair** [comment]
These changes merged as part of #87.

**Pull request closed without merging**
