### PR TITLE
add ontology_get_term_by_name query

### PR DESCRIPTION
**Pull request by zhlu9890**
- [ ] I updated the README.md docs to reflect this change.

For changes to the codebase:

- [x] I have written tests to cover this change.
- [x] This is not a breaking API change OR
- [ ] This is a breaking API change and I have incremented the API version and added a summary to CHANGELOG.md.

### CODE REVIEW

**Review by ialarmedalien — CHANGES_REQUESTED** [review]
Please write some tests for this query.

The [spec/test](https://github.com/kbase/relation_engine/tree/develop/spec/test) directory has numerous examples of how to set up test data and how to write the tests themselves. Once you have set up some test data, you can use it to test a number of stored queries.

**Review by slebras — APPROVED** [review]
lgtm, not sure what the testing framework for this repo looks like

**Comment by ialarmedalien** [comment]
> lgtm, not sure what the testing framework for this repo looks like

@slebras as I said in my comment, see the `spec/test` directory for examples

**Comment by zhlu9890** [comment]
@ialarmedalien, tests added.

**Review by ialarmedalien — APPROVED** [review]
👍

**Pull request merged**
